### ISSUE TITLE
Titanium project will not compile with this urbanairship module

### ISSUE THREAD

**Issue by jrsOnforce** [urbanairship/titanium-module#9]
We've been using Titanium for around 5 years and for many of them, using the old Urban Airship module - long time customers here.

Unfortunately, the older UA module crashes when we run any Titanium SDK greater than version 3.5.*.  

We're now being forced to upgrade to a much more recent version of Titanium SDK, which is forcing us to upgrade to your new UA SDK.

However, it seems that the new UA sdk is redefining entities, causing this crash below:

We use a few other Titanium modules, like ti.maps and some others that may be adding jars like google-play-services-base.jar and or google-play-services-gcm.jar..

```
[INFO] :   Generating /Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/res/values/theme.xml
[INFO] :   Packaging application: /Applications/android-sdk-macosx/build-tools/23.0.3/aapt "package" "-f" "-m" "-J" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/gen" "-M" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/AndroidManifest.xml" "-A" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/bin/assets" "-S" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/res" "-I" "/Applications/android-sdk-macosx/platforms/android-23/android.jar" "-F" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/bin/app.ap_" "--auto-add-overlay" "--extra-packages" "ti.modules.titanium.ui:android.support.v7.appcompat:android.support.v7.cardview:com.google.android.gms:com.urbanairship" "-S" "/var/folders/rf/8pxdk6bx775dptwwqjb6j3dh0001l0/T/116615-44475-7mfc86/res" "-S" "/var/folders/rf/8pxdk6bx775dptwwqjb6j3dh0001l0/T/116615-44475-1ys5cat/res" "-S" "/var/folders/rf/8pxdk6bx775dptwwqjb6j3dh0001l0/T/116615-44475-1ryhkvf/res"
[INFO] :   Building Java source files: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/javac "-J-Xmx1024M" "-encoding" "utf8" "-bootclasspath" "/Applications/android-sdk-macosx/platforms/android-23/android.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/kroll-v8.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-analytics.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/aps-analytics.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-android.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/jaxen-1.1.1.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/ti-commons-codec-1.3.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/kroll-common.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/titanium.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-app.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-ui.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/nineoldandroids-appc-2.4.0.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-filesystem.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-media.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-appcompat.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/android-support-v4.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/android-support-v7-appcompat.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-cardview.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/cardview-v7-23.0.1.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-locale.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-network.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-xml.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-utils.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-geolocation.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-accelerometer.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-contacts.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-map.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-gesture.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-calendar.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-platform.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-database.jar:/Library/Application Support/Titanium/modules/android/ti.paint/2.0.2/paint.jar:/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/ti.imagefactory/2.2.1/imagefactory.jar:/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/map.jar:/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/lib/google-play-services.jar:/Library/Application Support/Titanium/modules/android/ti.newrelic/4.0/ti_newrelic.jar:/Library/Application Support/Titanium/modules/android/ti.newrelic/4.0/lib/newrelic.android.jar:/Library/Application Support/Titanium/modules/android/yy.logcatcher/0.1/tilogcatcher.jar:/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/urbanairship.jar:/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/google-play-services-base.jar:/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/google-play-services-gcm.jar:/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/urbanairship-sdk-7.2.0.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/kroll-apt.jar:/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/lib/titanium-verify.jar:Manifest.class:R.class:AssetCryptImpl.class:OnforceActivity.class:OnforceAppInfo.class:OnforceApplication.class" "-d" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/bin/classes" "-proc:none" "-target" "1.6" "-source" "1.6" "@/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/java-sources.txt"
[INFO] :   Running dexer: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java "-javaagent:/Library/Application Support/Titanium/modules/android/ti.newrelic/4.0/class.rewriter.jar" "-Xmx1024M" "-XX:-UseGCOverheadLimit" "-Djava.ext.dirs=/Applications/android-sdk-macosx/platform-tools" "-jar" "/Applications/android-sdk-macosx/build-tools/23.0.3/lib/dx.jar" "--dex" "--output=/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/bin/classes.dex" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/build/android/bin/classes" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/lib/titanium-verify.jar" "/Library/Application Support/Titanium/modules/android/ti.paint/2.0.2/paint.jar" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/ti.imagefactory/2.2.1/imagefactory.jar" "/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/map.jar" "/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/lib/google-play-services.jar" "/Library/Application Support/Titanium/modules/android/ti.newrelic/4.0/ti_newrelic.jar" "/Library/Application Support/Titanium/modules/android/ti.newrelic/4.0/lib/newrelic.android.jar" "/Library/Application Support/Titanium/modules/android/yy.logcatcher/0.1/tilogcatcher.jar" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/urbanairship.jar" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/google-play-services-base.jar" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/google-play-services-gcm.jar" "/Users/jsplaine/svn/OF_mobile/branches/1.10/head/modules/android/com.urbanairship/1.3.0/lib/urbanairship-sdk-7.2.0.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/kroll-v8.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-analytics.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/aps-analytics.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-android.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/jaxen-1.1.1.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/ti-commons-codec-1.3.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/kroll-common.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/titanium.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-app.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-ui.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/nineoldandroids-appc-2.4.0.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-filesystem.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-media.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-appcompat.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/android-support-v4.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/android-support-v7-appcompat.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-cardview.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/cardview-v7-23.0.1.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-locale.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-network.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-xml.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-utils.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-geolocation.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-accelerometer.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-contacts.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-map.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-gesture.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-calendar.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-platform.jar" "/Users/jsplaine/Library/Application Support/Titanium/mobilesdk/osx/5.2.1.GA/android/modules/titanium-database.jar"
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  objc[44700]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEvent;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsRequest;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsResponse;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GoogleAuthException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GoogleAuthUtil;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/GooglePlayServicesAvailabilityException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/UserRecoverableAuthException;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :   at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :   at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :   at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :   ... 4 more
```

**Comment by ashcoding** [comment]
Hi @jrsOnforce, could you create a JIRA issue ticket and link it back to this issue? More info located here [http://docs.appcelerator.com/platform/latest/#!/guide/Reporting_Bugs_or_Requesting_Features](http://docs.appcelerator.com/platform/latest/#!/guide/Reporting_Bugs_or_Requesting_Features).

**Comment by rlepinski** [comment]
@jrsOnforce Yeah, you may need to remove the play services jar from the UA Module. 

@ashcoding Do you have any plans on supporting a stand alone google play service module, so other modules could depend on them instead of every module including the same jars?

**Comment by ashcoding** [comment]
There's no plans on that but that is a very very good suggestion.
